on:
  release:
    types: [published]

jobs:
  release-windows:
    name: Itch.io Windows Publish
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows
        id: download-windows
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: Project-Erebus-windows.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GH_CREDENTIALS }}"
      - name: Deploy to itch.io (Windows)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: Project Erebus
          ITCH_USER: Subwoof01
          PACKAGE: Project-Erebus-windows.zip
          VERSION: ${{ steps.download-windows.outputs.version }}